### ISSUE TITLE
Vulnerability CRLF injection in RestSharp >= 107.0.0 && < 120.0.0

### ISSUE THREAD

**Issue by IT-VBFK** [CompuMasterGmbH/CompuMaster.OpenCollaborationService#3]
https://github.com/restsharp/RestSharp/security/advisories/GHSA-4rr6-2v9v-wcpc

Manually bumping to 120.0.0 throws `MethodNotFoundException`.

**Comment by jochenwezel** [comment]
Hmm, the latest version of RestSharp per today is v112.1.0 (not 120.0.0)

The RestSharp component has got an update regarding RestSharp version + several others issues. See release v2024.11.05.100.
Therefore this issue is considered as closed.

**Comment by IT-VBFK** [comment]
Ou.. silly me :D 

Was obviously a typo.. however: thanks for this library and for fixing this 🎉
